---
language: generic

sudo: false

services:
  - docker

before_script:
  - npm install -g snyk
  - snyk auth "${SNYK_API_TOKEN}"

script:
  - docker build -t postorius .
  - snyk test --docker postorius

before_deploy:
  - if test -n "${TRAVIS_TAG}"; then
      docker tag postorius "ushi/postorius:${TRAVIS_TAG}" &&
        snyk monitor --docker "ushi/postorius:${TRAVIS_TAG}";
    else
      docker tag postorius "ushi/postorius:latest";
    fi
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

deploy:
  - provider: script
    skip_cleanup: true
    script: docker push "ushi/postorius:${TRAVIS_TAG}"
    on:
      tags: true

  - provider: script
    skip_cleanup: true
    script: docker push "ushi/postorius:latest"
    on:
      branch: master
